name: Prettier
on:
    pull_request:
    push:
        branches:
            - main

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.TOKEN }}
                  ref: ${{ github.head_ref }}

            - uses: actions/setup-node@v1
              with:
                  node-version: '16.x'
            - run: npm i prettier -g
            - run: npm run format:write

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  branch: main
                  commit_message: 'CI: fix formatting'
